coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: yes
    changes: no

ignore:
  - "lib/src/**/*.g.dart"

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default