// Mocks generated by Mockito 5.0.15 from annotations
// in yonomi_flutter_demo/test/provider/devices_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yonomi_platform_sdk/yonomi-sdk.dart' as _i2;

import 'devices_provider_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDevice_0 extends _i1.Fake implements _i2.Device {}

/// A class which mocks [GetDevicesFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDevicesFunction extends _i1.Mock
    implements _i3.GetDevicesFunction {
  MockGetDevicesFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Device>> call(_i2.Request? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [request],
        ),
        returnValue: Future<List<_i2.Device>>.value(<_i2.Device>[]),
      ) as _i4.Future<List<_i2.Device>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetDeviceDetailsFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDeviceDetailsFunction extends _i1.Mock
    implements _i3.GetDeviceDetailsFunction {
  MockGetDeviceDetailsFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Device> call(
    _i2.Request? request,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            request,
            id,
          ],
        ),
        returnValue: Future<_i2.Device>.value(_FakeDevice_0()),
      ) as _i4.Future<_i2.Device>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SendLockUnlockFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendLockUnlockFunction extends _i1.Mock
    implements _i3.SendLockUnlockFunction {
  MockSendLockUnlockFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(
    _i2.Request? request,
    String? id,
    bool? lockUnlock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            request,
            id,
            lockUnlock,
          ],
        ),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
